# -----------------------------------------------------------------------------
# GENERAL
# -----------------------------------------------------------------------------

# Load .bashrc, if available
if [ -f "$HOME/.bashrc" ]; then
    #shellcheck source=./.bashrc
    source "$HOME"/.bashrc
fi

# Start tmux, if available, when interactive, not nested and over SSH
if command -v tmux &> /dev/null && \
    [[ -n "$PS1" ]] && \
    [[ -z "$TMUX" ]] && \
    [[ -n "$SSH_CONNECTION" ]]; then
    tmux attach -t default || tmux new -s default
fi

# -----------------------------------------------------------------------------
# PATH
# -----------------------------------------------------------------------------

# Add a user-specific bin path, if available
if [ -d "$HOME/.bin" ]; then
    PATH=$PATH:~/.bin
fi

# Add a rust-specific Cargo bin path, if available
if [ -d "$HOME/.cargo/bin" ]; then
    PATH=$PATH:~/.cargo/bin
fi
